"""initial schema.

Revision ID: a669ef8f21b3
Revises:
Create Date: 2026-08-23 06:04:31.364763
"""
from typing import Sequence, Union

from alembic import context, op
import sqlalchemy as sa
from app.db_guards import assert_safe_downgrade



revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_rate_limit_counters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject_digest', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('window_epoch', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_digest', 'action', 'window_epoch', name='uq_auth_subject_window')
    )
    op.create_index(op.f('ix_auth_rate_limit_counters_action'), 'auth_rate_limit_counters', ['action'], unique=False)
    op.create_index(op.f('ix_auth_rate_limit_counters_subject_digest'), 'auth_rate_limit_counters', ['subject_digest'], unique=False)
    op.create_index(op.f('ix_auth_rate_limit_counters_window_epoch'), 'auth_rate_limit_counters', ['window_epoch'], unique=False)
    op.create_table('model_prices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('input_microusd_per_million', sa.BigInteger(), nullable=False),
    sa.Column('output_microusd_per_million', sa.BigInteger(), nullable=False),
    sa.Column('max_output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('input_microusd_per_million >= 0', name='model_input_price_nonnegative'),
    sa.CheckConstraint('output_microusd_per_million >= 0', name='model_output_price_nonnegative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model', 'version', name='uq_model_price_version')
    )
    op.create_index(op.f('ix_model_prices_active'), 'model_prices', ['active'], unique=False)
    op.create_index(op.f('ix_model_prices_model'), 'model_prices', ['model'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic', sa.String(length=80), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_reference'), 'outbox_events', ['reference'], unique=False)
    op.create_index(op.f('ix_outbox_events_status'), 'outbox_events', ['status'], unique=False)
    op.create_index(op.f('ix_outbox_events_topic'), 'outbox_events', ['topic'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('access_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_digest', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_sessions_token_digest'), 'access_sessions', ['token_digest'], unique=True)
    op.create_index(op.f('ix_access_sessions_user_id'), 'access_sessions', ['user_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('secret_digest', sa.String(length=64), nullable=False),
    sa.Column('last_four', sa.String(length=4), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_status'), 'api_keys', ['status'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('limit_microusd', sa.BigInteger(), nullable=False),
    sa.Column('reserved_microusd', sa.BigInteger(), nullable=False),
    sa.Column('spent_microusd', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('limit_microusd > 0', name='budget_limit_positive'),
    sa.CheckConstraint('reserved_microusd >= 0', name='budget_reserved_nonnegative'),
    sa.CheckConstraint('spent_microusd + reserved_microusd <= limit_microusd', name='budget_within_limit'),
    sa.CheckConstraint('spent_microusd >= 0', name='budget_spent_nonnegative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_status'), 'budgets', ['status'], unique=False)
    op.create_index(op.f('ix_budgets_user_id'), 'budgets', ['user_id'], unique=False)
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_digest', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_digest', name='uq_email_verify_token_digest')
    )
    op.create_index(op.f('ix_email_verification_tokens_token_digest'), 'email_verification_tokens', ['token_digest'], unique=False)
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.create_table('ledger_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('reference', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_transactions_idempotency_key'), 'ledger_transactions', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_ledger_transactions_kind'), 'ledger_transactions', ['kind'], unique=False)
    op.create_index(op.f('ix_ledger_transactions_reference'), 'ledger_transactions', ['reference'], unique=False)
    op.create_index(op.f('ix_ledger_transactions_user_id'), 'ledger_transactions', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_digest', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_digest', name='uq_password_reset_token_digest')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_digest'), 'password_reset_tokens', ['token_digest'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('payment_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('amount_microusd', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('provider_transaction_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount_microusd > 0', name='payment_amount_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_transaction_id')
    )
    op.create_index(op.f('ix_payment_orders_status'), 'payment_orders', ['status'], unique=False)
    op.create_index(op.f('ix_payment_orders_user_id'), 'payment_orders', ['user_id'], unique=False)
    op.create_table('wallets',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('balance_microusd', sa.BigInteger(), nullable=False),
    sa.Column('reserved_microusd', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('balance_microusd >= 0', name='wallet_balance_nonnegative'),
    sa.CheckConstraint('reserved_microusd >= 0', name='wallet_reserved_nonnegative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('ledger_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('account', sa.String(length=48), nullable=False),
    sa.Column('amount_microusd', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount_microusd != 0', name='ledger_entry_nonzero'),
    sa.ForeignKeyConstraint(['transaction_id'], ['ledger_transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_account'), 'ledger_entries', ['account'], unique=False)
    op.create_index(op.f('ix_ledger_entries_transaction_id'), 'ledger_entries', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_user_id'), 'ledger_entries', ['user_id'], unique=False)
    op.create_index('ix_ledger_user_created', 'ledger_entries', ['user_id', 'created_at'], unique=False)
    op.create_table('model_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('api_key_id', sa.String(length=32), nullable=False),
    sa.Column('budget_id', sa.String(length=36), nullable=True),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('requested_model', sa.String(length=120), nullable=False),
    sa.Column('final_model', sa.String(length=120), nullable=True),
    sa.Column('final_provider', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('price_version', sa.Integer(), nullable=False),
    sa.Column('input_price', sa.BigInteger(), nullable=False),
    sa.Column('output_price', sa.BigInteger(), nullable=False),
    sa.Column('reserved_microusd', sa.BigInteger(), nullable=False),
    sa.Column('charged_microusd', sa.BigInteger(), nullable=False),
    sa.Column('upstream_cost_microusd', sa.BigInteger(), nullable=False),
    sa.Column('input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('usage_estimated', sa.Boolean(), nullable=False),
    sa.Column('fallback_count', sa.Integer(), nullable=False),
    sa.Column('failure_category', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('charged_microusd >= 0', name='request_charged_nonnegative'),
    sa.CheckConstraint('reserved_microusd >= 0', name='request_reserved_nonnegative'),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_request_user_idempotency')
    )
    op.create_index('ix_model_request_user_created', 'model_requests', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_model_requests_api_key_id'), 'model_requests', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_model_requests_created_at'), 'model_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_model_requests_status'), 'model_requests', ['status'], unique=False)
    op.create_index(op.f('ix_model_requests_user_id'), 'model_requests', ['user_id'], unique=False)
    op.create_table('payment_webhook_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.String(length=120), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('raw_digest', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['payment_orders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'event_id', name='uq_payment_provider_event')
    )
    op.create_index(op.f('ix_payment_webhook_events_order_id'), 'payment_webhook_events', ['order_id'], unique=False)
    op.create_table('rate_limit_counters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('api_key_id', sa.String(length=32), nullable=False),
    sa.Column('window_epoch', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_id', 'window_epoch', name='uq_rate_key_window')
    )
    op.create_index(op.f('ix_rate_limit_counters_api_key_id'), 'rate_limit_counters', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_rate_limit_counters_window_epoch'), 'rate_limit_counters', ['window_epoch'], unique=False)
    op.create_table('operator_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['model_requests.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operator_actions_action'), 'operator_actions', ['action'], unique=False)
    op.create_index(op.f('ix_operator_actions_request_id'), 'operator_actions', ['request_id'], unique=False)
    op.create_table('provider_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('failure_category', sa.String(length=80), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['model_requests.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'ordinal', name='uq_request_attempt_ordinal')
    )
    op.create_index(op.f('ix_provider_attempts_request_id'), 'provider_attempts', ['request_id'], unique=False)
    # Ledger history is append-only at the database boundary.  The application
    # service already enforces this invariant, but PostgreSQL must also protect
    # it from an accidental admin UPDATE/DELETE or a compromised app role.
    if op.get_bind().dialect.name == "postgresql":
        op.execute(sa.text("""
            CREATE OR REPLACE FUNCTION kunlun_reject_ledger_mutation()
            RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN
                RAISE EXCEPTION 'ledger history is append-only: % on %', TG_OP, TG_TABLE_NAME
                    USING ERRCODE = '55000';
            END;
            $$;
        """))
        op.execute(sa.text("""
            CREATE OR REPLACE FUNCTION kunlun_check_ledger_transaction_balance()
            RETURNS trigger LANGUAGE plpgsql AS $$
            DECLARE
                transaction_total bigint;
                transaction_id_value varchar(36);
            BEGIN
                transaction_id_value := COALESCE(NEW.transaction_id, OLD.transaction_id);
                SELECT COALESCE(SUM(amount_microusd), 0)
                  INTO transaction_total
                  FROM ledger_entries
                 WHERE transaction_id = transaction_id_value;
                IF transaction_total <> 0 THEN
                    RAISE EXCEPTION 'unbalanced ledger transaction: % (sum=%)',
                        transaction_id_value, transaction_total
                        USING ERRCODE = '23514';
                END IF;
                RETURN NULL;
            END;
            $$;
        """))
        op.execute(sa.text("""
            CREATE TRIGGER ledger_transactions_no_update
            BEFORE UPDATE ON ledger_transactions
            FOR EACH ROW EXECUTE FUNCTION kunlun_reject_ledger_mutation()
        """))
        op.execute(sa.text("""
            CREATE TRIGGER ledger_transactions_no_delete
            BEFORE DELETE ON ledger_transactions
            FOR EACH ROW EXECUTE FUNCTION kunlun_reject_ledger_mutation()
        """))
        op.execute(sa.text("""
            CREATE TRIGGER ledger_entries_no_update
            BEFORE UPDATE ON ledger_entries
            FOR EACH ROW EXECUTE FUNCTION kunlun_reject_ledger_mutation()
        """))
        op.execute(sa.text("""
            CREATE TRIGGER ledger_entries_no_delete
            BEFORE DELETE ON ledger_entries
            FOR EACH ROW EXECUTE FUNCTION kunlun_reject_ledger_mutation()
        """))
        op.execute(sa.text("""
            CREATE CONSTRAINT TRIGGER ledger_entries_balance_deferred
            AFTER INSERT OR UPDATE OR DELETE ON ledger_entries
            DEFERRABLE INITIALLY DEFERRED
            FOR EACH ROW EXECUTE FUNCTION kunlun_check_ledger_transaction_balance()
        """))
    # ### end Alembic commands ###


def downgrade() -> None:
    allow_destructive_downgrade = context.config.attributes.get("allow_destructive_downgrade", False)
    environment = context.config.attributes.get("environment", "development")
    assert_safe_downgrade(environment, bool(allow_destructive_downgrade))
    if op.get_bind().dialect.name == "postgresql":
        op.execute(sa.text("DROP TRIGGER IF EXISTS ledger_entries_no_delete ON ledger_entries"))
        op.execute(sa.text("DROP TRIGGER IF EXISTS ledger_entries_no_update ON ledger_entries"))
        op.execute(sa.text("DROP TRIGGER IF EXISTS ledger_entries_balance_deferred ON ledger_entries"))
        op.execute(sa.text("DROP TRIGGER IF EXISTS ledger_transactions_no_delete ON ledger_transactions"))
        op.execute(sa.text("DROP TRIGGER IF EXISTS ledger_transactions_no_update ON ledger_transactions"))
        op.execute(sa.text("DROP FUNCTION IF EXISTS kunlun_check_ledger_transaction_balance()"))
        op.execute(sa.text("DROP FUNCTION IF EXISTS kunlun_reject_ledger_mutation()"))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_attempts_request_id'), table_name='provider_attempts')
    op.drop_table('provider_attempts')
    op.drop_index(op.f('ix_operator_actions_request_id'), table_name='operator_actions')
    op.drop_index(op.f('ix_operator_actions_action'), table_name='operator_actions')
    op.drop_table('operator_actions')
    op.drop_index(op.f('ix_rate_limit_counters_window_epoch'), table_name='rate_limit_counters')
    op.drop_index(op.f('ix_rate_limit_counters_api_key_id'), table_name='rate_limit_counters')
    op.drop_table('rate_limit_counters')
    op.drop_index(op.f('ix_payment_webhook_events_order_id'), table_name='payment_webhook_events')
    op.drop_table('payment_webhook_events')
    op.drop_index(op.f('ix_model_requests_user_id'), table_name='model_requests')
    op.drop_index(op.f('ix_model_requests_status'), table_name='model_requests')
    op.drop_index(op.f('ix_model_requests_created_at'), table_name='model_requests')
    op.drop_index(op.f('ix_model_requests_api_key_id'), table_name='model_requests')
    op.drop_index('ix_model_request_user_created', table_name='model_requests')
    op.drop_table('model_requests')
    op.drop_index('ix_ledger_user_created', table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_user_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_transaction_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_account'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_payment_orders_user_id'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_status'), table_name='payment_orders')
    op.drop_table('payment_orders')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_digest'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_ledger_transactions_user_id'), table_name='ledger_transactions')
    op.drop_index(op.f('ix_ledger_transactions_reference'), table_name='ledger_transactions')
    op.drop_index(op.f('ix_ledger_transactions_kind'), table_name='ledger_transactions')
    op.drop_index(op.f('ix_ledger_transactions_idempotency_key'), table_name='ledger_transactions')
    op.drop_table('ledger_transactions')
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_token_digest'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_index(op.f('ix_budgets_user_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_status'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_status'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_access_sessions_user_id'), table_name='access_sessions')
    op.drop_index(op.f('ix_access_sessions_token_digest'), table_name='access_sessions')
    op.drop_table('access_sessions')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_outbox_events_topic'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_status'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_reference'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_model_prices_model'), table_name='model_prices')
    op.drop_index(op.f('ix_model_prices_active'), table_name='model_prices')
    op.drop_table('model_prices')
    op.drop_index(op.f('ix_auth_rate_limit_counters_window_epoch'), table_name='auth_rate_limit_counters')
    op.drop_index(op.f('ix_auth_rate_limit_counters_subject_digest'), table_name='auth_rate_limit_counters')
    op.drop_index(op.f('ix_auth_rate_limit_counters_action'), table_name='auth_rate_limit_counters')
    op.drop_table('auth_rate_limit_counters')
    # ### end Alembic commands ###
